# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pip install --no-cache-dir ansible==6.4.0 \
      ansible-lint==6.7.0 && sudo apt install cowsay -y
